install:
    - rm -rf public || exit 0

script:
    - ./hugo_travis_ci

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: docs
    target-branch: main
    github_token: $github_token
    on:
        branch: source

