title: Tsenguunjav Byambasuren
description: Ph.D. Candidate in Applied Economics, Cornell University
logo: /assets/img/headshot.png
#theme: jekyll-theme-minimal
#github:
#  is_user_page: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
